var stories = [
  { label: "Your story", emoji: "+", neutral: true },
  { label: "maya", emoji: "🌿" },
  { label: "ravi", emoji: "☕" },
  { label: "lena_art", emoji: "🎨" },
  { label: "dan.k", emoji: "⛰️" }
];

var posts = [
  {
    type: "ai-blocked",
    user: "sunsets.daily",
    badge: "ai generated",
    badgeType: "ai",
    time: "47 minutes ago",
    avatar: "AI",
    likes: "",
    caption: "",
    comments: []
  },
  {
    type: "human",
    user: "maya_explores",
    badge: "human",
    badgeType: "human",
    time: "3 minutes ago",
    avatar: "🌿",
    likes: "122 likes",
    caption: "Keeping this app small on purpose. Two photos from a slower afternoon.",
    comments: [
      { user: "ravi", text: "This is the exact energy." },
      { user: "lena_art", text: "Way calmer than modern feeds." }
    ]
  },
  {
    type: "ai-image",
    user: "studio.pro2",
    badge: "human",
    badgeType: "human",
    time: "1 hour ago",
    avatar: "P",
    image: "../docs/img1.png",
    likes: "89 likes",
    caption: " posted for vacation.",
    comments: [
      { user: "evan", text: "Beautiful." },
      { user: "maya", text: "The framing feels righ" }
    ]
  }
];




function scenicThumb(left) {
  if (left) {
    return 'data:image/svg+xml;charset=UTF-8,' + encodeURIComponent(
      '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 180 180">' +
        '<rect width="180" height="180" fill="#5a7eb0"/>' +
        '<rect x="18" y="86" width="20" height="68" fill="#223758"/>' +
        '<rect x="44" y="56" width="26" height="98" fill="#34507f"/>' +
        '<rect x="76" y="78" width="18" height="76" fill="#294264"/>' +
        '<rect x="102" y="44" width="24" height="110" fill="#466fa8"/>' +
        '<rect x="132" y="64" width="28" height="90" fill="#36598b"/>' +
        '<g fill="#f8f0b4">' +
          '<rect x="24" y="96" width="4" height="6"/><rect x="24" y="108" width="4" height="6"/>' +
          '<rect x="50" y="66" width="4" height="6"/><rect x="58" y="78" width="4" height="6"/>' +
          '<rect x="82" y="90" width="4" height="6"/><rect x="108" y="54" width="4" height="6"/>' +
          '<rect x="116" y="68" width="4" height="6"/><rect x="138" y="76" width="4" height="6"/>' +
        '</g>' +
      '</svg>'
    );
  }

  return 'data:image/svg+xml;charset=UTF-8,' + encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 180 180">' +
      '<defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#ffb24a"/><stop offset="100%" stop-color="#f16f59"/></linearGradient></defs>' +
      '<rect width="180" height="180" fill="url(#g)"/>' +
      '<circle cx="90" cy="92" r="30" fill="#ffd36d"/>' +
      '<path d="M0 130 L38 100 L70 128 L104 86 L144 126 L180 100 L180 180 L0 180 Z" fill="#934641"/>' +
      '<path d="M0 146 L52 110 L84 136 L124 96 L180 134 L180 180 L0 180 Z" fill="#6f3040"/>' +
    '</svg>'
  );
}

function renderStories() {
  var root = document.getElementById("stories-list");

  root.innerHTML = stories.map(function (story) {
    var ringClass = story.neutral ? "story-ring neutral" : "story-ring";

    return [
      '<article class="story">',
      '  <div class="' + ringClass + '">',
      '    <div class="story-inner">' + story.emoji + "</div>",
      "  </div>",
      '  <span class="story-label">' + story.label + "</span>",
      "</article>"
    ].join("");
  }).join("");
}

function renderPostBody(post) {
  if (post.type === "ai-blocked") {
    return [
      '<div class="post-body ai-blocked">',
      '  <div class="ai-message">',
      '    <div class="ai-emoji">🤖</div>',
      '    <p>This content was generated by AI and is not recommended</p>',
      '    <span class="show-link">Show anyway</span>',
      "  </div>",
      "</div>"
    ].join("");
  }

  if (post.type === "human") {
    return [
      '<div class="post-body human-scene">',
      '  <div class="photo-pair">',
      '    <img class="mini-photo" src="' + scenicThumb(true) + '" alt="City photo">',
      '    <img class="mini-photo" src="' + scenicThumb(false) + '" alt="Sunset photo">',
      "  </div>",
      "</div>"
    ].join("");
  }

  return [
    '<div class="post-body ai-image-wrap">',
    '  <img src="' + post.image + '" alt="AI generated reference image">',
    "</div>"
  ].join("");
}

function renderPostCopy(post) {
  if (post.type === "ai-blocked") {
    return "";
  }

  var comments = post.comments.map(function (comment) {
    return '<p class="comment"><strong>' + comment.user + '</strong> ' + comment.text + '</p>';
  }).join("");

  return [
    '<div class="post-actions" aria-hidden="true">',
    "  <span>♥</span>",
    "  <span>▢</span>",
    "  <span>✈</span>",
    "</div>",
    '<div class="post-copy">',
    '  <p class="likes">' + post.likes + "</p>",
    '  <p class="caption"><strong>' + post.user + '</strong> ' + post.caption + "</p>",
    comments,
    "</div>"
  ].join("");
}

function renderFeed() {
  var root = document.getElementById("feed-list");

  root.innerHTML = posts.map(function (post) {
    return [
      '<article class="post-card">',
      '  <header class="post-head">',
      '    <div class="post-user">',
      '      <div class="post-avatar">' + post.avatar + "</div>",
      '      <div class="post-meta">',
      '        <div class="meta-top">',
      '          <strong>' + post.user + "</strong>",
      '          <span class="chip ' + post.badgeType + '">' + post.badge + "</span>",
      "        </div>",
      '        <div class="post-time">' + post.time + "</div>",
      "      </div>",
      "    </div>",
      '    <div class="post-menu">⋮</div>',
      "  </header>",
      renderPostBody(post),
      renderPostCopy(post),
      "</article>"
    ].join("");
  }).join("");
}

renderStories();
renderFeed();
